- name: put values
  template: src=values.yml dest=/tmp/docker-registry-{{ docker_registry_helm_release }}.yml

- name: upgrade {{ docker_registry_helm_release }} release using a Helm chart
  shell: helm upgrade {{ docker_registry_helm_release }} stable/docker-registry --install --namespace {{ k8s_namespace }} -f /tmp/docker-registry-{{ docker_registry_helm_release }}.yml
